### ISSUE TITLE
Appsflyer late initialization (GDPR)

### ISSUE THREAD

**Issue by afdima** [Tealium/tealium-android-appsflyer-remote-command#8]
If you call `AppsFlyerLib.getInstance().startTracking()` after activity super.onReume() you will not get deeplink and onAppOpenAttribution call. Add API for clients if they do late initialize, they need to pass activity instance to `startTracking()` instead of deprecated `trackAppLaunch()`. cc @af-fess

**Comment by tamayok** [comment]
@afdima @af-fess In the event that initialization needs to happen later, I believe calling the remote command for `initialize` would cover this. However, I couldn't find any AppsFlyer API for `startTracking()` that would take an activity instance. Looks like all take an `application` is that correct? Did I overlook something? Thanks in advance!

**Comment by tamayok** [comment]
Thought about this a little more. I'll make an adjustment for this. Thank you.

**Comment by afdima** [comment]
@tamayok since appsflyer version 5.2.0 you can pass activity instance to `startTracking`
